version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.amazonaws:aws-java-sdk-sqs
    versions:
    - 1.11.1000
    - 1.11.942
    - 1.11.946
    - 1.11.950
    - 1.11.954
    - 1.11.959
    - 1.11.964
    - 1.11.969
    - 1.11.974
    - 1.11.979
    - 1.11.986
    - 1.11.991
    - 1.11.996
  - dependency-name: com.amazonaws:aws-java-sdk-bom
    versions:
    - 1.11.1000
    - 1.11.942
    - 1.11.946
    - 1.11.950
    - 1.11.954
    - 1.11.959
    - 1.11.964
    - 1.11.969
    - 1.11.974
    - 1.11.979
    - 1.11.986
    - 1.11.991
    - 1.11.996
  - dependency-name: com.microsoft.azure:azure-servicebus
    versions:
    - 3.6.0
    - 3.6.1
    - 3.6.2
